### ISSUE TITLE
how to run ruby interpreter?

### ISSUE THREAD

**Issue by afucher** [hostilefork/whitespacers#2]
Hi,

Can u tell how can I run the ruby interpreter??

Thks in advance.

**Comment by hostilefork** [comment]
Hi,

I didn't write it, just put it in the repository for some comparisons *(the author is [Wayne Contrad](https://github.com/wconrad))*.

I've written all of [one Ruby program](http://blog.hostilefork.com/imagination-squared-plus-openzoom/), five years ago *(geez, that long!?)*, and don't know a whole lot about the language.  But given this program is simple, I can see the `$<` is where the input is coming from, and predictably that is standard input:

http://stackoverflow.com/a/4279689/211160

So when you run it, you should be able to type until end of file.  On UNIX that means you get to type until you do Ctrl-D in your console, and if you're on a Windows system you indicate an end to typed input with Ctrl-Z.  So you would just enter code with tabs, spaces, and newlines (and every other character "is a comment").

If you would rather make a file in a text editor, then do so and call that program program.ws.

Assuming you are on a unix system, the first line of the script (`#!/usr/bin/ruby1.8`) locates your ruby installation.  If that's not the path to your ruby, you can find out by typing `which ruby` and substitute that path after the `#!`.  Then mark the script executable with `chmod +x whitespace.rb`.

After that type at the shell prompt:

    whitespace.rb < program.ws

That should pipe the program into the standard input.

For an interesting study in contrasts, note what I did in the long, experimental, educational Rebol implementation (which abuses a PARSE dialect instead of ordinary code).  The language has symbols which are mapped to string values for `tab`, `space` and `char`... so I just take a block of those symbols and have an operation that merges a block of them into a string.  Convenient input form for testing...

https://github.com/hostilefork/whitespacers/blob/master/rebol/whitespace.reb#L738
